AUT=SmartHeatingHMI
CWD=.
ENVVARS=envvars
HOOK_SUB_PROCESSES=false
IMPLICITAUTSTART=0
LANGUAGE=Python
OBJECTMAPSTYLE=script
TEST_CASES=tst_test_reset tst_test_boundary_values tst_test_temperature_data_driven tst_test_synchronization tst_test_backend_status tst_test_e2e_heating
VERSION=3
WRAPPERS=Qt
